In [227]:
import pandas as pd

In [ ]:
df = pd.read_excel("data/physics_code.xlsx")

In [229]:
df.shape

(48, 13)

In [230]:
df.head(5)

,title,code,num_lines,num_char,pde_class,phys_process,phys_valid,num_method,obf_vars,obf_comments,corruption_source_idx,corruption_source_pde,injected_comments
0,Wave_Comm_Valid_1,import numpy as np\n\n#Def of the initial cond...,93,7904,Wave Equation,oscillation/restoration,Yes,explicit,False,NaN,NaN,NaN,NaN
1,Wave_Comm_Valid_2,import numpy as np\n\n# Initial Condition\n\nd...,75,3256,Wave Equation,oscillation/restoration,Yes,explicit,False,NaN,NaN,NaN,NaN
2,Wave_Comm_Valid_3,import numpy as np\n\nfrom scipy.integrate imp...,53,1332,Wave Equation,oscillation/restoration,Yes,explicit/implicit,False,NaN,NaN,NaN,NaN
3,Wave_Comm_Valid_4,import numpy as np\n\n\n\ndef spectral_wave_so...,43,1084,Wave Equation,oscillation/restoration,Yes,spectral,False,NaN,NaN,NaN,NaN
4,Heat_Comm_Valid_1,import numpy as np\n\nfrom scipy.integrate imp...,35,845,Heat Equation,diffusion,Yes,implicit,False,NaN,NaN,NaN,NaN

In [231]:
if "obf_vars" in df.columns:
    del df["obf_vars"]
if "obf_comments" in df.columns:
    del df["obf_comments"]
if "obf_comments" in df.columns:
    del df["obf_comments"]

### Fix columns

In [232]:
# Add gt_sample column
df["gt_sample"] = df["title"].str.split("_").str[0] + "_" + df["title"].str.split("_").str[-1]
df["gt_sample"] = df["gt_sample"].astype(str)

In [233]:
df["gt_sample"].value_counts()

gt_sample
Wave_1            3
Wave_2            3
Wave_3            3
Wave_4            3
Heat_1            3
Heat_2            3
Heat_3            3
Heat_4            3
Burgers_1         3
Burgers_2         3
Burgers_3         3
Burgers_4         3
NavierStokes_1    3
NavierStokes_2    3
NavierStokes_3    3
NavierStokes_4    3
Name: count, dtype: int64

In [234]:
df["phys_valid"].value_counts()

phys_valid
Yes    32
No     16
Name: count, dtype: int64

In [235]:
# Change to boolean
if type(df["phys_valid"][0]) == str:
    df["phys_valid"] = (df["phys_valid"] == "Yes")
df["phys_valid"].value_counts()

phys_valid
True     32
False    16
Name: count, dtype: int64

In [236]:
# Add mod_type column
df["mod_type"] = df["title"].str.split("_").str[1] + "_" + df["title"].str.split("_").str[2]
df["mod_type"] = df["mod_type"].astype(str)
df["mod_type"].value_counts()

mod_type
Comm_Valid        16
NoComm_Valid      16
NoComm_InValid    16
Name: count, dtype: int64

In [237]:
df.dtypes

title                        str
code                         str
num_lines                  int64
num_char                   int64
pde_class                    str
phys_process                 str
phys_valid                  bool
num_method                   str
corruption_source_idx    float64
corruption_source_pde    float64
injected_comments        float64
gt_sample                    str
mod_type                     str
dtype: object

In [238]:
df["pde_class_1"] = df["pde_class"].str.replace(r"\b([A-Za-z]+) Equation\b", r"\1", regex=True)
df["pde_class_1"] = df["pde_class_1"].str.lower().str.replace(" ", "-", regex=False)
df["pde_class"] = df["pde_class_1"]
del df["pde_class_1"]
df["pde_class"].value_counts()

pde_class
wave             12
heat             12
burgers          12
navier-stokes    12
Name: count, dtype: int64

In [239]:
df["phys_process"].value_counts()

phys_process
oscillation/restoration             12
diffusion                           12
advection/diffusion                 12
advection-diffusion                  6
advection-difffusion-restoration     3
advection-diffusion-restoration      3
Name: count, dtype: int64

In [240]:
# Replace - with /
df["phys_process"] = df["phys_process"].str.lower().str.replace("-", "/", regex=False)
df["phys_process"].value_counts()

phys_process
oscillation/restoration             12
diffusion                           12
advection/diffusion                 12
advection/diffusion                  6
advection/difffusion/restoration     3
advection/diffusion/restoration      3
Name: count, dtype: int64

In [241]:
# Replace - with /
df["num_method"] = df["num_method"].str.lower().str.replace("-", "/", regex=False)
df["num_method"].value_counts()

num_method
explicit                      21
explicit/implicit             12
spectral                       3
implicit                       3
explicit/implicit              3
spectral/explicit              3
explicit/implicit/spectral     3
Name: count, dtype: int64

In [242]:
df.head(5)

,title,code,num_lines,num_char,pde_class,phys_process,phys_valid,num_method,corruption_source_idx,corruption_source_pde,injected_comments,gt_sample,mod_type
0,Wave_Comm_Valid_1,import numpy as np\n\n#Def of the initial cond...,93,7904,wave,oscillation/restoration,True,explicit,NaN,NaN,NaN,Wave_1,Comm_Valid
1,Wave_Comm_Valid_2,import numpy as np\n\n# Initial Condition\n\nd...,75,3256,wave,oscillation/restoration,True,explicit,NaN,NaN,NaN,Wave_2,Comm_Valid
2,Wave_Comm_Valid_3,import numpy as np\n\nfrom scipy.integrate imp...,53,1332,wave,oscillation/restoration,True,explicit/implicit,NaN,NaN,NaN,Wave_3,Comm_Valid
3,Wave_Comm_Valid_4,import numpy as np\n\n\n\ndef spectral_wave_so...,43,1084,wave,oscillation/restoration,True,spectral,NaN,NaN,NaN,Wave_4,Comm_Valid
4,Heat_Comm_Valid_1,import numpy as np\n\nfrom scipy.integrate imp...,35,845,heat,diffusion,True,implicit,NaN,NaN,NaN,Heat_1,Comm_Valid

In [243]:
df.dtypes

title                        str
code                         str
num_lines                  int64
num_char                   int64
pde_class                    str
phys_process                 str
phys_valid                  bool
num_method                   str
corruption_source_idx    float64
corruption_source_pde    float64
injected_comments        float64
gt_sample                    str
mod_type                     str
dtype: object

In [244]:
for i, j in zip(df.columns, df.dtypes.values.tolist()):
    print(f"{i} ({str(j)})")

title (str)
code (str)
num_lines (int64)
num_char (int64)
pde_class (str)
phys_process (str)
phys_valid (bool)
num_method (str)
corruption_source_idx (float64)
corruption_source_pde (float64)
injected_comments (float64)
gt_sample (str)
mod_type (str)

In [245]:
df.head(3)

,title,code,num_lines,num_char,pde_class,phys_process,phys_valid,num_method,corruption_source_idx,corruption_source_pde,injected_comments,gt_sample,mod_type
0,Wave_Comm_Valid_1,import numpy as np\n\n#Def of the initial cond...,93,7904,wave,oscillation/restoration,True,explicit,NaN,NaN,NaN,Wave_1,Comm_Valid
1,Wave_Comm_Valid_2,import numpy as np\n\n# Initial Condition\n\nd...,75,3256,wave,oscillation/restoration,True,explicit,NaN,NaN,NaN,Wave_2,Comm_Valid
2,Wave_Comm_Valid_3,import numpy as np\n\nfrom scipy.integrate imp...,53,1332,wave,oscillation/restoration,True,explicit/implicit,NaN,NaN,NaN,Wave_3,Comm_Valid

In [249]:
df.to_excel("data/pdedata.xlsx")